import Header from "@/components/Header";
import { Eye, Shield, Newspaper, Zap, Brain, FileText } from "lucide-react";

const HowItWorks = () => {
  const steps = [
    {
      icon: FileText,
      title: "Paste Your Text",
      description: "Copy and paste any news article, social media post, or written content you want to analyze. The tool works best with English text.",
    },
    {
      icon: Brain,
      title: "AI Analysis",
      description: "Our AI model examines the text for linguistic patterns, rhetorical devices, and structural elements commonly associated with bias and manipulation.",
    },
    {
      icon: Zap,
      title: "Get Results",
      description: "Receive a comprehensive breakdown including bias indicators, propaganda techniques, and AI-writing detection scores with explanations.",
    },
  ];

  const features = [
    {
      icon: Eye,
      title: "Bias Detection",
      description: "Identifies politically charged language, one-sided framing, and emotionally manipulative phrasing that may indicate bias in reporting.",
    },
    {
      icon: Shield,
      title: "Propaganda Analysis",
      description: "Detects common propaganda techniques such as fear appeals, bandwagon effects, false dichotomies, and ad hominem attacks.",
    },
    {
      icon: Newspaper,
      title: "AI Writing Detection",
      description: "Analyzes writing patterns to estimate the likelihood that content was generated by AI rather than written by a human.",
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="container mx-auto px-4 py-12 md:py-16">
        {/* Hero */}
        <section className="text-center mb-16">
          <h1 className="font-display text-4xl md:text-5xl font-bold text-foreground mb-4">
            How NewsLens Works
          </h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            A simple three-step process to help you understand the content you consume.
          </p>
        </section>

        {/* Steps */}
        <section className="mb-20">
          <div className="grid md:grid-cols-3 gap-8">
            {steps.map((step, index) => (
              <div key={step.title} className="relative">
                <div className="bg-card border border-border rounded-xl p-6 h-full">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-lg bg-secondary flex items-center justify-center">
                      <step.icon className="w-5 h-5 text-secondary-foreground" />
                    </div>
                    <span className="text-sm font-medium text-muted-foreground">Step {index + 1}</span>
                  </div>
                  <h3 className="font-display text-xl font-semibold text-foreground mb-2">
                    {step.title}
                  </h3>
                  <p className="text-muted-foreground text-sm leading-relaxed">
                    {step.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Features Detail */}
        <section className="mb-16">
          <h2 className="font-display text-2xl md:text-3xl font-bold text-foreground mb-8 text-center">
            What We Analyze
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            {features.map((feature) => (
              <div key={feature.title} className="bg-card border border-border rounded-xl p-6">
                <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4">
                  <feature.icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="font-display text-lg font-semibold text-foreground mb-2">
                  {feature.title}
                </h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* Disclaimer */}
        <section className="max-w-3xl mx-auto">
          <div className="bg-muted/50 border border-border rounded-xl p-6">
            <h3 className="font-display text-lg font-semibold text-foreground mb-2">
              Important Disclaimer
            </h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              NewsLens provides interpretive analysis based on language patterns and AI models. 
              It does not fact-check or verify claims. Results represent one analytical perspective 
              and should not be taken as definitive truth. We encourage users to consult multiple 
              sources and form their own conclusions. Confidence scores indicate pattern matching 
              strength, not certainty.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
};

export default HowItWorks;
